# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0002_auto_20160208_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa1.Question'),
        ),
    ]
