# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0002_auto_20160224_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Set2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_set2_text', models.CharField(max_length=200)),
                ('mcq_question_set', models.ManyToManyField(to='qa1.Mcq_Question')),
            ],
        ),
    ]
