# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0003_question_set2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_question',
            name='tag1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='tag2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='tag3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='question_set',
            field=models.ManyToManyField(to='qa1.Question_Set'),
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='subject_set',
            field=models.ManyToManyField(to='qa1.Subject'),
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='tag_set',
            field=models.ManyToManyField(to='qa1.Tag'),
        ),
    ]
