# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0004_auto_20160224_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_question',
            name='question_set',
            field=models.ManyToManyField(blank=True, null=True, to='qa1.Question_Set'),
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='subject_set',
            field=models.ManyToManyField(blank=True, null=True, to='qa1.Subject'),
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='tag_set',
            field=models.ManyToManyField(blank=True, null=True, to='qa1.Tag'),
        ),
    ]
