# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='phote',
            field=models.ImageField(upload_to=b'images'),
        ),
    ]
