# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0007_auto_20160224_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_text',
        ),
    ]
