# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0008_auto_20160224_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='phote',
            new_name='photo',
        ),
    ]
