# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa1', '0010_markedtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedtext',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
