# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0011_markedtext_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markedtext',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
