# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0013_auto_20160229_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='question_set',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='question_set2',
            name='mcq_question_set',
        ),
        migrations.RemoveField(
            model_name='mcq_question',
            name='question_set',
        ),
        migrations.RemoveField(
            model_name='mcq_question',
            name='subject_set',
        ),
        migrations.RemoveField(
            model_name='mcq_question',
            name='tag_set',
        ),
        migrations.DeleteModel(
            name='Question_Set',
        ),
        migrations.DeleteModel(
            name='Question_Set2',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
