# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0014_auto_20160303_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_question',
            name='choice_e',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='choice_f',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='mcq_answer2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='tag4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='tag5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
