# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0015_auto_20160303_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcq_question',
            options={},
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/mcq/'),
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='explanation_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
