# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0016_auto_20160304_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_set_text', models.CharField(max_length=200, verbose_name='Question Set')),
                ('mcq_question', models.ManyToManyField(blank=True, null=True, to='qa1.Mcq_Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_topic_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question_set',
            name='question_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa1.QuestionTopic'),
        ),
    ]
