# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0018_auto_20160304_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_topic',
            name='question_topic_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
