# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0020_auto_20160304_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_question',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date: '),
        ),
    ]
