# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0021_mcq_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_question',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editing Date: '),
        ),
    ]
