# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0022_mcq_question_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_set',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editing Date: '),
        ),
        migrations.AddField(
            model_name='question_set',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date: '),
        ),
    ]
