# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0025_auto_20160307_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_question',
            name='mcq_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/mcq/'),
        ),
    ]
