# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0026_mcq_question_mcq_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_set',
            name='individual_mcq_marks',
            field=models.IntegerField(default=1, verbose_name='Individual Mcq Question Marks: '),
        ),
        migrations.AddField(
            model_name='question_set',
            name='negative_marking_percentage',
            field=models.IntegerField(default=0, verbose_name='Percent Of Marks To Be Deducted For Wrong Answer: '),
        ),
    ]
