# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0027_auto_20160308_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_set',
            name='individual_mcq_time',
            field=models.IntegerField(default=60, verbose_name='Individual Mcq Question Time In Second: '),
        ),
    ]
