# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0020_remove_readingcontent_mcq_question'),
        ('qa1', '0028_question_set_individual_mcq_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_question',
            name='reading_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingTopic'),
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='subtopic1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.SubTopic1'),
        ),
    ]
