# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa1', '0029_auto_20160426_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marked_Mcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa1.Mcq_Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='marked_mcq',
            unique_together=set([('user', 'mcq_question')]),
        ),
    ]
