# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0030_auto_20160503_0022'),
        ('qa1', '0030_auto_20160503_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_set',
            name='reading_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingContent'),
        ),
        migrations.AddField(
            model_name='question_topic',
            name='is_topic_wise',
            field=models.BooleanField(default=False, verbose_name='Is Topic Wise'),
        ),
    ]
