# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0031_auto_20160503_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_topic',
            old_name='is_topic_wise',
            new_name='is_reading_content',
        ),
    ]
