# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0030_auto_20160503_0022'),
        ('qa1', '0032_auto_20160503_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_set',
            name='reading_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingTopic'),
        ),
        migrations.AddField(
            model_name='question_set',
            name='subtopic1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.SubTopic1', verbose_name='Sub Topic Name'),
        ),
    ]
