# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa1', '0033_auto_20160504_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Set_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Publishing Date: ')),
                ('finish_date', models.DateTimeField(verbose_name='Editing Date: ')),
                ('marks', models.IntegerField(default=0, verbose_name='Marks Obtained: ')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa1.Question_Set')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Result',
            },
        ),
        migrations.AlterUniqueTogether(
            name='question_set_result',
            unique_together=set([('user', 'question_set')]),
        ),
    ]
