# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0034_auto_20160507_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_set_result',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
