# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0036_question_set_result_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_set_result',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
