# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0037_auto_20160507_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_set_result',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
    ]
