# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_auto_20160507_1727'),
        ('qa1', '0038_auto_20160507_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_set',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Conformation'),
        ),
        migrations.AddField(
            model_name='question_set',
            name='special_plan',
            field=models.ManyToManyField(to='subscription.Special_Plan'),
        ),
        migrations.AddField(
            model_name='question_set',
            name='subscription_plan',
            field=models.ManyToManyField(to='subscription.Subscription_Plan'),
        ),
    ]
