# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0039_auto_20160507_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_set',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Is Free'),
        ),
    ]
