# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0040_auto_20160522_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_set',
            name='is_free2',
            field=models.BooleanField(default=True, verbose_name='Is Free'),
        ),
    ]
