# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0041_question_set_is_free2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_set',
            name='is_free2',
        ),
    ]
