# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0032_contentnotes_reading_topic'),
        ('qa1', '0042_remove_question_set_is_free2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_set',
            name='reading_content',
        ),
        migrations.AddField(
            model_name='question_set',
            name='content',
            field=models.ManyToManyField(to='readingmaterial.ReadingContent'),
        ),
    ]
