# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0043_auto_20160522_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_set',
            old_name='content',
            new_name='reading_content',
        ),
    ]
