# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0033_auto_20160522_1417'),
        ('qa1', '0046_remove_question_set_special_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_question',
            name='reading_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingContent', verbose_name='Reading Content  '),
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='reading_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingTopic', verbose_name='Topic '),
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='subtopic1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.SubTopic1', verbose_name='Sub-Topic'),
        ),
    ]
