# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0047_auto_20160602_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_set',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exam End Date: '),
        ),
        migrations.AddField(
            model_name='question_set',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exam Start Date: '),
        ),
    ]
