# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_set_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question_set',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Topic'),
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='question_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.Question_Set'),
            preserve_default=False,
        ),
    ]
