# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan_title', models.CharField(max_length=200)),
                ('subscription_fee', models.IntegerField(verbose_name='Subscription Fee')),
                ('subscription_duration', models.IntegerField(verbose_name='Subscription Duration(In Days)')),
                ('can_create_blog_tag', models.BooleanField(default=True, verbose_name='Can Create Blog Tag')),
                ('no_of_random_question', models.IntegerField(blank=True, null=True, verbose_name='Subscription Duration(In Days)')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
            },
        ),
    ]
