# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_plan',
            name='no_of_random_question',
            field=models.IntegerField(default=-1, verbose_name='No Of Random Question'),
        ),
        migrations.AlterField(
            model_name='subscription_plan',
            name='subscription_duration',
            field=models.IntegerField(default=30, verbose_name='Subscription Duration(In Days)'),
        ),
    ]
