# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20160427_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_plan',
            name='subscription_duration',
            field=models.IntegerField(default=-1, verbose_name='Subscription Duration(In Days)'),
        ),
    ]
