# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20160427_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan',
            name='no_of_exam_per_day',
            field=models.IntegerField(default=-1, verbose_name='No Of Exam Per Day'),
        ),
    ]
