# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 05:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0006_subscription_plan_no_of_exam_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('request_date', models.DateTimeField(verbose_name='Request Date: ')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date: ')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date: ')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Conformation')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription_Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
