# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 06:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_auto_20160428_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan',
            name='bkash_no',
            field=models.CharField(default='01521253206', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 6, 39, 34, 102730, tzinfo=utc), verbose_name='Request Date: '),
        ),
    ]
