# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_auto_20160428_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='no_of_exam_per_day',
            field=models.IntegerField(default=-1, verbose_name='No Of Exam Per Day'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='no_of_random_question',
            field=models.IntegerField(default=0, verbose_name='No Of Random Question'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 7, 40, 1, 956010, tzinfo=utc), verbose_name='Request Date: '),
        ),
    ]
