# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 11:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_auto_20160428_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_plan_title', models.CharField(max_length=200)),
                ('special_plan_fee', models.IntegerField(default=0, verbose_name='Subscription Fee')),
                ('bkash_no', models.CharField(default='01521253206', max_length=200)),
            ],
            options={
                'verbose_name': 'Special Plan',
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 11, 2, 5, 953294, tzinfo=utc), verbose_name='Request Date: '),
        ),
    ]
