# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 11:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0011_auto_20160507_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Special_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('request_date', models.DateTimeField(default=datetime.datetime(2016, 5, 7, 11, 11, 47, 472579, tzinfo=utc), verbose_name='Request Date: ')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Conformation')),
                ('special_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Special_Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Of Special Plan',
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 11, 11, 47, 471509, tzinfo=utc), verbose_name='Request Date: '),
        ),
    ]
