# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_auto_20160507_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 11, 27, 42, 12117, tzinfo=utc), verbose_name='Request Date: '),
        ),
        migrations.AlterField(
            model_name='subscription_special_plan',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 11, 27, 42, 12861, tzinfo=utc), verbose_name='Request Date: '),
        ),
    ]
