# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_auto_20160507_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special_plan',
            options={'verbose_name': 'Special Subscription Plan'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription Of Regular Plan'},
        ),
        migrations.AlterModelOptions(
            name='subscription_plan',
            options={'verbose_name': 'Regular Subscription Plan'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 12, 17, 21, 563639, tzinfo=utc), verbose_name='Request Date: '),
        ),
        migrations.AlterField(
            model_name='subscription_special_plan',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 12, 17, 21, 564654, tzinfo=utc), verbose_name='Request Date: '),
        ),
    ]
