# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_auto_20160523_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 12, 18, 22, 616381, tzinfo=utc), verbose_name='Request Date: '),
        ),
        migrations.AlterField(
            model_name='subscription_special_plan',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 12, 18, 22, 617184, tzinfo=utc), verbose_name='Request Date: '),
        ),
    ]
