# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0046_remove_question_set_special_plan'),
        ('subscription', '0015_auto_20160523_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_special_plan',
            name='special_plan',
        ),
        migrations.RemoveField(
            model_name='subscription_special_plan',
            name='user',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 12, 22, 56, 249096, tzinfo=utc), verbose_name='Request Date: '),
        ),
        migrations.DeleteModel(
            name='Special_Plan',
        ),
        migrations.DeleteModel(
            name='Subscription_Special_Plan',
        ),
    ]
