# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 13:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0016_auto_20160523_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 13, 18, 16, 696618, tzinfo=utc), verbose_name='Request Date: '),
        ),
    ]
