# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0017_auto_20160523_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Conform'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 13, 19, 19, 703486, tzinfo=utc), verbose_name='Request Date: '),
        ),
    ]
