# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 09:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0019_auto_20160523_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('request_date', models.DateTimeField(default=datetime.datetime(2016, 5, 25, 9, 56, 39, 522533, tzinfo=utc), verbose_name='Request Date: ')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date: ')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date: ')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Conform')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Valid')),
                ('no_of_exam_per_day', models.IntegerField(default=-1, verbose_name='No Of Exam Per Day')),
                ('no_of_random_question', models.IntegerField(default=0, verbose_name='No Of Random Question')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription_Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Of Regular Plan',
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 9, 56, 39, 521743, tzinfo=utc), verbose_name='Request Date: '),
        ),
        migrations.AlterUniqueTogether(
            name='subscription_request',
            unique_together=set([('user', 'subscription_plan', 'is_valid', 'is_confirmed')]),
        ),
    ]
