# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0020_auto_20160525_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription_request',
            options={'verbose_name': 'Subscription Request'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 9, 58, 51, 987095, tzinfo=utc), verbose_name='Request Date: '),
        ),
        migrations.AlterField(
            model_name='subscription_request',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='subscription_request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 9, 58, 51, 987888, tzinfo=utc), verbose_name='Request Date: '),
        ),
        migrations.AlterUniqueTogether(
            name='subscription_request',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subscription_request',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription_request',
            name='no_of_exam_per_day',
        ),
        migrations.RemoveField(
            model_name='subscription_request',
            name='no_of_random_question',
        ),
        migrations.RemoveField(
            model_name='subscription_request',
            name='start_date',
        ),
    ]
