# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 10:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0021_auto_20160525_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 10, 37, 28, 661060, tzinfo=utc), verbose_name='Request Date: '),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='token',
        ),
    ]
