# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editing Date: '),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date: '),
        ),
    ]
