# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20160428_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notification',
            name='is_forall',
            field=models.BooleanField(default=True, verbose_name='For All User'),
        ),
    ]
