# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0029_auto_20160426_1135'),
        ('links', '0003_auto_20160426_1052'),
        ('notice', '0006_auto_20160424_1141'),
        ('readingmaterial', '0028_auto_20160426_1458'),
        ('announcement', '0004_user_notification_is_forall'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notification',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.Link'),
        ),
        migrations.AddField(
            model_name='user_notification',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notice.Notice'),
        ),
        migrations.AddField(
            model_name='user_notification',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa1.Question_Set'),
        ),
        migrations.AddField(
            model_name='user_notification',
            name='reading_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingContent'),
        ),
    ]
