# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_auto_20160428_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_notification',
            old_name='links',
            new_name='link',
        ),
    ]
