# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
