# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20160424_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_text',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Notice '),
        ),
    ]
