# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20160424_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice_file1',
            new_name='file1',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='notice_file2',
            new_name='file2',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='notice_file3',
            new_name='file3',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='notice_image1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='notice_image2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='notice_image3',
            new_name='image3',
        ),
    ]
