"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r@3r*_7h7hvbg(1*4r^(9(_dc@ph2m$w4y-5d4y39g5l$bm@*&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'qa1',
    'exam',
    'blog',
    'dashboard',
    'feedback',


    'readingmaterial',
    'question',
    'notice',
    'links',
    'announcement',
    'subscription',

    # 'django_comments',
    'django_wysiwyg',
    'ckeditor',
    'ckeditor_uploader',
    # 'filemanager',
    'social.apps.django_app.default',



    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'django.contrib.sites',

]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
                # "social_auth.context_processors.social_auth_by_type_backends",

            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
       
        'TEST': {
            'NAME': os.path.join(BASE_DIR, 'db_test.sqlite3'),
            # 'TEST_MIRROR': 'default',
        }
    },

    # 'replica': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #     'OPTIONS':{
    #         'timeout': 180,
    #     },
    #     'TEST_MIRROR': 'default'


    # }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/




LOGIN_REDIRECT_URL='/login/'

AUTHENTICATION_BACKENDS = (
    'social.backends.google.GoogleOAuth2',
    'social.backends.open_id.OpenIdAuth',
    'social.backends.google.GoogleOpenId',

    'social.backends.google.GoogleOAuth',
    'social.backends.twitter.TwitterOAuth',
    'social.backends.yahoo.YahooOpenId',
    'social.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend', # default
   
)


ANONYMOUS_USER_ID = -1

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "")


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

SITE_ID = 1


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'onlinebcs25@gmail.com'
EMAIL_HOST_PASSWORD = 'passwordpassword19'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

DJANGO_WYSIWYG_FLAVOR = "ckeditor"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_MEDIA_URL = '/static/third-party/ckeditor'
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"


CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_REQUIRE_STAFF=False
AWS_QUERYSTRING_AUTH = False



CKEDITOR_CONFIGS = {
    'awesome_ckeditor': {
        'toolbar': 'Basic',
    },

    'default': {
        'toolbar': 'basic',
        'height': 300,
        'width': '100%',
        # # 'styles': { 'background-color': 'red' },
        #  'skin': 'office2013',
    },

    'text_field': {
        'toolbar': 'basic',
        'height': 100,
        'width': '100%',
        # # 'styles': { 'background-color': 'red' },
        #  'skin': 'office2013',
    },



}




    
SOCIAL_AUTH_ENABLED_BACKENDS = ('google', 'github')
TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_processors.auth',
    'django.core.context_processors.debug',
    'django.core.context_processors.i18n',
    'django.core.context_processors.media',
    'django.contrib.messages.context_processors.messages',
    'social.apps.django_app.context_processors.backends',
)

SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/dashboard/'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '346364116120-lq8uvhk84h94e9klb727cr6tdlc1epso.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'pY6fhZZT-tCW8y2iZZO9QpG4'


# for onlinebce
# SOCIAL_AUTH_FACEBOOK_KEY = '1802984556596131'
# SOCIAL_AUTH_FACEBOOK_SECRET = 'd8d9981a8e7ff3ca094997c6fd1e0097'

#for test account

# SOCIAL_AUTH_FACEBOOK_KEY = '1802989976595589'
# SOCIAL_AUTH_FACEBOOK_SECRET = 'b300ea443357a3a344cbbf4539e3e5a6'


SOCIAL_AUTH_FACEBOOK_KEY = '1803116059916314'
SOCIAL_AUTH_FACEBOOK_SECRET = 'b2399b031ed324083634f1edd83e9173'





# FACEBOOK_APP_ID='1802984556596131'
# FACEBOOK_API_SECRET='d8d9981a8e7ff3ca094997c6fd1e0097'






SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))
# MEDIA_ROOT = "/mnt/02C8B1A8C8B199FD/programme/python/linux/pro1/mysite/"
