# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='ReadingTopic',
        ),
        migrations.RenameField(
            model_name='readingtopic',
            old_name='topic_text',
            new_name='reading_topic_text',
        ),
    ]
