# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0002_auto_20160301_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingcontent',
            name='reading_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingTopic'),
        ),
    ]
