# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0003_readingcontent_reading_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic2',
            name='subtopic1',
        ),
        migrations.RemoveField(
            model_name='readingcontent',
            name='subtopic2',
        ),
        migrations.DeleteModel(
            name='SubTopic2',
        ),
    ]
