# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0013_auto_20160229_1616'),
        ('readingmaterial', '0005_contentmarkedmcq_contentmarkedtext_contentnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmarkedmcq',
            name='mcq_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa1.Mcq_Question'),
        ),
    ]
