# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0006_contentmarkedmcq_mcq_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingcontent',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/content/'),
        ),
        migrations.AddField(
            model_name='readingcontent',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/content/'),
        ),
        migrations.AddField(
            model_name='readingcontent',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/content/'),
        ),
    ]
