# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0010_contentcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentcomment',
            old_name='post',
            new_name='content',
        ),
    ]
