# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0013_readingcontent_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcomment',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editing Date: '),
        ),
        migrations.AddField(
            model_name='contentcomment',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date: '),
        ),
    ]
