# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0017_quick_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quick_question',
            old_name='user',
            new_name='uploader',
        ),
    ]
