# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0019_auto_20160426_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingcontent',
            name='mcq_question',
        ),
    ]
