# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0020_remove_readingcontent_mcq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingcontent',
            name='content_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
