# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0021_auto_20160426_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingcontent',
            name='reading_topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingTopic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readingcontent',
            name='subtopic1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.SubTopic1', verbose_name='Sub Topic Name'),
        ),
    ]
