# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0022_auto_20160426_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic1',
            options={'verbose_name': 'Sub Topic Of Content'},
        ),
        migrations.AddField(
            model_name='subtopic1',
            name='tid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
