# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0023_auto_20160426_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic1',
            name='tid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Topic Id'),
        ),
    ]
