# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0024_auto_20160426_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quick_question',
            options={'verbose_name': 'Quick/Short Question(Tika)'},
        ),
    ]
