# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0025_auto_20160426_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quick_question',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingContent'),
            preserve_default=False,
        ),
    ]
