# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0026_auto_20160426_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingcontent',
            name='stid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sub Topic Id'),
        ),
        migrations.AddField(
            model_name='readingcontent',
            name='tid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Topic Id'),
        ),
    ]
