# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0027_auto_20160426_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingtopic',
            options={'verbose_name': 'Topic Of Reading Content'},
        ),
    ]
