# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0029_marked_quick_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marked_quick_question',
            unique_together=set([('user', 'quick_question')]),
        ),
    ]
