# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readingmaterial', '0030_auto_20160503_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingContent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='finished_content',
            unique_together=set([('user', 'reading_content')]),
        ),
    ]
