# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0031_auto_20160504_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnotes',
            name='reading_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingTopic'),
        ),
    ]
