# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 08:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0032_contentnotes_reading_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingcontent',
            name='content_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
