# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readingmaterial', '0033_auto_20160522_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingcontent',
            name='subtopic1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.SubTopic1', verbose_name='Sub-Topic'),
        ),
    ]
