# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qa1', '0029_auto_20160426_1135'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readingmaterial', '0028_auto_20160426_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date: ')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='Editing Date: ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message/Objection From User',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date: ')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='Editing Date: ')),
                ('mcq_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa1.Mcq_Question')),
                ('quick_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.Quick_Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report/Correction Suggestion From User',
            },
        ),
    ]
