# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0047_auto_20160602_2236'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readingmaterial', '0034_auto_20160603_2032'),
        ('feedback', '0007_auto_20160603_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Mcq_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date: ')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='Editing Date: ')),
                ('mcq_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa1.Mcq_Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report/Correction From User For MCQ',
            },
        ),
        migrations.CreateModel(
            name='Report_Quick_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date: ')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='Editing Date: ')),
                ('mcq_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qa1.Mcq_Question')),
                ('quick_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.Quick_Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report/Correction  From User Quick Question',
            },
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='report',
            name='mcq_question',
        ),
        migrations.RemoveField(
            model_name='report',
            name='quick_question',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AlterUniqueTogether(
            name='report_quick_question',
            unique_together=set([('user', 'quick_question')]),
        ),
        migrations.AlterUniqueTogether(
            name='report_mcq_question',
            unique_together=set([('user', 'mcq_question')]),
        ),
    ]
