# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160229_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editing Date: '),
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date: '),
        ),
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editing Date: '),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publishing Date: '),
        ),
    ]
