# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 05:58
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_post_body2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
