# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 06:05
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160522_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_body2',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
