# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 09:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160522_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body Of Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_text',
            field=models.CharField(max_length=200, verbose_name='Title: '),
        ),
    ]
