# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 04:25
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_post_body2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_body2',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Body Of Post'),
        ),
    ]
