# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readingmaterial', '0012_auto_20160305_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_question_from_excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readingmaterial.ReadingContent')),
            ],
        ),
    ]
