# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20160306_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload_question_from_excel',
            options={'permissions': (('can_upload_mcq_from_excel', 'This User Will be able to upload bulk mcq from a excel file'),)},
        ),
        migrations.AlterField(
            model_name='upload_question_from_excel',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='resource_files/'),
        ),
    ]
