# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20160306_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload_question_from_excel',
            options={'permissions': (('can_upload_mcq_from_excel', 'can_upload_mcq_from_excel'),)},
        ),
    ]
