# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20160306_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload_question_from_excel',
            options={'permissions': (('excel_upload', 'excel_upload'),)},
        ),
    ]
