# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_upload_question_set_from_excel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload_question_set_from_excel',
            options={'permissions': (('excel_question_set_upload', 'excel_question_set_upload'),)},
        ),
    ]
